version: '3.8'

services:
  nexus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-repo
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
      - ./nexus-init:/opt/sonatype/nexus/etc/scripts
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Dnexus.scripts.allowCreation=true
    restart: unless-stopped
    networks:
      - sak-network

volumes:
  nexus-data:

networks:
  sak-network:
    external: true
