version: "3.9"

services:
  mysql:
    build:
      context: .
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myapplication
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sak-network

networks:
  sak-network:
    driver: bridge
    name: sak-network

volumes:
  mysql_data:
